export const ErrorCodeEnum={
    AUTH_EMAIL_ALREADY_EXISTS:"AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN:"AUTH_INVALID_TOKEN",
    AUTH_USER_NOT_FOUND:"AUTH_USER_NOT_FOUND",

    AUTH_NOT_FOUND:"AUTH_NOT_FOUND",
    AUTH_TOO_MANY_REQUESTS:"AUTH_TOO_MANY_REQUESTS",
    AUTH_UNAUTHORIZED_ACCESS:"AUTH_UNAUTHORIZED_ACCESS",
    AUTH_TOKEN_NOT_FOUND:"AUTH_TOKEN_NOT_FOUND",

    //VALIDATION and resource error
    VALIDATION_ERROR:"VALIDATION_ERROR",
    RESOUIRCE_NOT_FOUND:"RESOUIRCE_NOT_FOUND",

    //System Error
    INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeType=keyof typeof ErrorCodeEnum;